### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by MartinHjelmare** [zwave-js/zwave-js-server#163]
## Description

I'm testing server 1.2.0 and getting this error.

```
New client
zjs             | 11:44:27.381 CNTRLR   [Node 010] treating BasicCC Set as a report
zjs             | This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
zjs             | TypeError: Cannot read property 'type' of undefined
zjs             |     at Object.dumpMetadata (/app/node_modules/@zwave-js/server/dist/lib/state.js:42:24)
zjs             |     at /app/node_modules/@zwave-js/server/dist/lib/forward.js:91:58
zjs             |     at Array.forEach (<anonymous>)
zjs             |     at notifyNodeOnValueOrMetadataUpdates (/app/node_modules/@zwave-js/server/dist/lib/forward.js:86:34)
zjs             |     at ZWaveNode.<anonymous> (/app/node_modules/@zwave-js/server/dist/lib/forward.js:147:21)
zjs             |     at ZWaveNode.emit (events.js:315:20)
zjs             |     at ZWaveNode.EventEmitter.emit (domain.js:467:12)
zjs             |     at ZWaveNode.translateValueEvent (/app/node_modules/zwave-js/src/lib/node/Node.ts:346:8)
zjs             |     at ValueDB.emit (events.js:315:20)
zjs             |     at ValueDB.EventEmitter.emit (domain.js:467:12)
```

**Comment by MartinHjelmare** [comment]
AlCalzone's discord comment:
> notifyNodeOnValueOrMetadataUpdates gets called for the value and metadata events. args is the argument that's emitted by zwave-js.
That never has a metadata property on the prevValue or newValue properties
