### ISSUE TITLE
Error details not always returned

### ISSUE THREAD

**Issue by cgarwood** [zwave-js/zwave-js-server#302]
Noticed this while working on the heal node UI in HA by passing an invalid node ID... The first time I get:

```
2021-07-13 19:08:53 DEBUG (MainThread) [zwave_js_server] Publishing message:
{'command': 'controller.heal_node',
 'messageId': '1d1f9a6865f94291af0bb9fb7cef8d40',
 'nodeId': 99}

2021-07-13 19:08:53 DEBUG (MainThread) [zwave_js_server] Received message:
WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":false,"messageId":"1d1f9a6865f94291af0bb9fb7cef8d40","errorCode":"zwave_error","zwaveErrorCode":25,"zwaveErrorMessage":"Node 99 was not found!"}', extra='')
```

On subsequent attempts I only get the following until I restart the server:
```
2021-07-13 19:14:10 DEBUG (MainThread) [zwave_js_server] Publishing message:
{'command': 'controller.heal_node',
 'messageId': '77f37e08385d40e3bf65928b8c534184',
 'nodeId': 99}

2021-07-13 19:14:10 DEBUG (MainThread) [zwave_js_server] Received message:
WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":true,"messageId":"77f37e08385d40e3bf65928b8c534184","result":{"success":false}}', extra='')
```

**Comment by cgarwood** [comment]
May be a driver issue. In the driver logs I get this the first time, and nothing on subsequent attempts.
```
2021-07-13 23:30:38.140 ERROR ZWAVE-SERVER: Z-Wave error Node 99 was not found!
ZWaveError: Node 99 was not found!
at Map.<anonymous> (/usr/src/app/node_modules/zwave-js/src/lib/controller/Controller.ts:234:11)
at ZWaveController.healNode (/usr/src/app/node_modules/zwave-js/src/lib/controller/Controller.ts:1668:27)
at Function.handle (/usr/src/app/node_modules/@zwave-js/server/dist/lib/controller/message_handler.js:35:57)
at Object.controller (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:35:103)
at Client.receiveMessage (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:91:99)
at WebSocket.<anonymous> (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:44:45)
at WebSocket.emit (node:events:394:28)
at WebSocket.emit (node:domain:470:12)
at Receiver.receiverOnMessage (/usr/src/app/node_modules/ws/lib/websocket.js:835:20)
at Receiver.emit (node:events:394:28)
```

**Comment by raman325** [comment]
Yeah that seems to be a driver issue, going to transfer this over there

**Comment by raman325** [comment]
actually you may want to just close and reopen over there so that you can use their issue template

**Comment by cgarwood** [comment]
https://github.com/zwave-js/node-zwave-js/issues/3014
