### ISSUE TITLE
options var used without being initialized when configPath is not specified in 1.12.0 server

### ISSUE THREAD

**Issue by ashleybone** [zwave-js/zwave-js-server#453]
When starting the zwave-js server without specifying a config path, the options variable is not initialized but is then used in server.js:

```
Unable to start driver TypeError: Cannot use 'in' operator to search for 'emitValueUpdateAfterSetValue' in undefined
    at /usr/lib/node_modules/@zwave-js/server/dist/bin/server.js:85:42
    at Object.<anonymous> (/usr/lib/node_modules/@zwave-js/server/dist/bin/server.js:134:3)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by ashleybone** [comment]
Great, thanks!
