### ISSUE TITLE
npm update failed with registry error

### ISSUE THREAD

**Issue by AWSb24** [zwave-js/zwave-js-server#488]
I tried to update from 1.11.0 to 1.14.0 but it failed with the following information in the log file:

```
885 verbose stack HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/@zwave-js%2f.devcontainer - Not found
885 verbose stack     at /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
885 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
885 verbose stack     at async Arborist.[nodeFromEdge] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1066:19)
885 verbose stack     at async Arborist.[buildDepStep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:935:11)
885 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:216:7)
885 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:149:5)
885 verbose stack     at async Update.exec (/usr/lib/node_modules/npm/lib/commands/update.js:55:5)
885 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:66:5)
886 verbose statusCode 404
887 verbose pkgid @zwave-js/.devcontainer@*
888 verbose cwd /home/pi
889 verbose Linux 5.10.63-v7+
890 verbose argv "/usr/bin/node" "/usr/bin/npm" "update" "-g"
891 verbose node v16.13.0
892 verbose npm  v8.3.0
893 error code E404
894 error 404 Not Found - GET https://registry.npmjs.org/@zwave-js%2f.devcontainer - Not found
895 error 404
896 error 404  '@zwave-js/.devcontainer@*' is not in this registry.
897 error 404 You should bug the author to publish it (or use the name yourself!)
898 error 404
898 error 404 Note that you can also install from a
899 error 404 tarball, folder, http url, or git url.
900 verbose exit 1
901 timing npm Completed in 18812ms
902 verbose unfinished npm timer reify 1641315356897
903 verbose unfinished npm timer reify:loadTrees 1641315357011
904 verbose code 1
905 error A complete log of this run can be found in:
905 error     /root/.npm/_logs/2022-01-04T16_55_54_832Z-debug-0.log
```

Surprisingly, I did an update on my second RPI some minutes before and no error appeared.

**Comment by balloob** [comment]
You've entered the wrong command, it tries to fetch `https://registry.npmjs.org/@zwave-js%2f.devcontainer` Not sure where you got the devcontainer string from.
