### ISSUE TITLE
 Module '"zwave-js"' has no exported member 'InclusionGrant'.

### ISSUE THREAD

**Issue by rexopl** [zwave-js/zwave-js-server#540]
After some system and packages updates I get this error.
Maybe some one could help to resolve.
Versio 1.15.0
```
 $ ts-node src/bin/server.ts /dev/ttyACM0
TSError: ⨯ Unable to compile TypeScript:
src/lib/server.ts:3:18 - error TS2305: Module '"zwave-js"' has no exported member 'InclusionGrant'.

3 import { Driver, InclusionGrant, ZWaveError, ZWaveErrorCodes } from "zwave-js";
                   ~~~~~~~~~~~~~~

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)

```

**Comment by raman325** [comment]
sounds like you may be on an older version of zwave-js somehow. Separately this is not a supported installation method for the server and this hasn't been an issue for any of those supported methods.

**Comment by rexopl** [comment]
Hi, thanks looks like update zwave-js in another place, after updating it in proper folder all works ok.
