### ISSUE TITLE
Failed to compile/start the node server

### ISSUE THREAD

**Issue by infamouscoder** [zwave-js/zwave-js-server#673]
/usr/local/lib/node_modules/ts-node/src/index.ts:843
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/lib/forward.ts:52:49 - error TS2345: Argument of type '"node found"' is not assignable to parameter of type 'keyof ControllerEventCallbacks'.

52     this.clientsController.driver.controller.on("node found", (node) => {
                                                   ~~~~~~~~~~~~
src/lib/forward.ts:52:64 - error TS7006: Parameter 'node' implicitly has an 'any' type.

52     this.clientsController.driver.controller.on("node found", (node) => {
                                                                  ~~~~

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:843:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:847:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:1057:36)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1411:41)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1596:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1600:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  diagnosticCodes: [ 2345, 7006 ]
}

**Comment by infamouscoder** [comment]
Documentation missing to mention to upgrade to Node v18.
