### ISSUE TITLE
Fibaro Walli Roller Shutter Up and down buttons do not work

### ISSUE THREAD

**Issue by fhuebner2** [zwave-js/zwave-js-server#87]
Hi,

Fibaro's Walli Roller Shutter up, down and stop buttons do not work. They bring the message "error calling service: cover/open_cover. None".

But: The position slider works.

Home-assistant.log:
`2021-02-04 19:42:36 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2839114776] None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/cover.py", line 83, in async_open_cover
    await self.info.node.async_set_value(target_value, PRESS_BUTTON)
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/model/node.py", line 248, in async_set_value
    val = self.values[val]
KeyError: None
`

**Comment by AlCalzone** [comment]
Not related to the driver, so I'm moving this.

**Comment by marcelveldt** [comment]
Please report issues about the Home Assistant integration on the Home Assistant issue tracker.
This issue will be resolved in the next patch release (2021.2.1)
